import os
from dotenv import load_dotenv

# 从 .env 加载运行配置到进程环境变量。
load_dotenv()

# 以太坊 RPC 节点地址（HTTP）。
RPC_URL = os.getenv("RPC_URL")
# Telegram Bot Token。
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
# Telegram 聊天窗口 ID（消息推送目标）。
CHAT_ID = os.getenv("CHAT_ID")


def _get_int_env(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except (TypeError, ValueError):
        return default


def _get_float_env(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return float(raw)
    except (TypeError, ValueError):
        return default


def _get_bool_env(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    value = str(raw).strip().lower()
    if value in {"1", "true", "yes", "on"}:
        return True
    if value in {"0", "false", "no", "off"}:
        return False
    return default


def _get_str_env(name: str, default: str) -> str:
    raw = os.getenv(name)
    if raw is None:
        return default
    value = str(raw).strip()
    return value or default


def _get_csv_env(name: str, default: list[str]) -> list[str]:
    raw = os.getenv(name)
    if raw is None:
        return list(default)
    values = [str(item).strip() for item in str(raw).split(",")]
    return [item for item in values if item] or list(default)


# 价格服务配置。
PRICE_TTL_SEC = _get_int_env("PRICE_TTL_SEC", 30)
PRICE_FAIL_TTL_SEC = _get_int_env("PRICE_FAIL_TTL_SEC", 120)
PRICE_REQUEST_TIMEOUT_SEC = _get_int_env("PRICE_REQUEST_TIMEOUT_SEC", 6)
PRICE_MAX_CONCURRENCY = _get_int_env("PRICE_MAX_CONCURRENCY", 8)

# Signal Quality Gate 配置。
QUALITY_GATE_MIN_GLOBAL_USD = _get_float_env("QUALITY_GATE_MIN_GLOBAL_USD", 800.0)
QUALITY_GATE_STABLE_TRANSFER_MIN_USD = _get_float_env("QUALITY_GATE_STABLE_TRANSFER_MIN_USD", 2000.0)
QUALITY_GATE_MIN_TOKEN_LIQUIDITY_USD = _get_float_env("QUALITY_GATE_MIN_TOKEN_LIQUIDITY_USD", 200000.0)
QUALITY_GATE_MIN_PRICE_IMPACT_RATIO = _get_float_env("QUALITY_GATE_MIN_PRICE_IMPACT_RATIO", 0.003)
QUALITY_GATE_MIN_RELATIVE_ADDRESS_SIZE = _get_float_env("QUALITY_GATE_MIN_RELATIVE_ADDRESS_SIZE", 1.2)
QUALITY_GATE_MIN_TOKEN_VOLUME_RATIO = _get_float_env("QUALITY_GATE_MIN_TOKEN_VOLUME_RATIO", 0.001)
QUALITY_GATE_COOLDOWN_SEC = _get_int_env("QUALITY_GATE_COOLDOWN_SEC", 180)
QUALITY_GATE_REQUIRE_NON_NORMAL_BEHAVIOR = _get_bool_env("QUALITY_GATE_REQUIRE_NON_NORMAL_BEHAVIOR", False)
QUALITY_GATE_SCORE_THRESHOLD = _get_float_env("QUALITY_GATE_SCORE_THRESHOLD", 0.69)
QUALITY_GATE_TIER1_THRESHOLD = _get_float_env("QUALITY_GATE_TIER1_THRESHOLD", 0.84)
QUALITY_GATE_TIER2_THRESHOLD = _get_float_env("QUALITY_GATE_TIER2_THRESHOLD", 0.75)
QUALITY_GATE_STABLE_NON_SWAP_HARD_FILTER_USD = _get_float_env("QUALITY_GATE_STABLE_NON_SWAP_HARD_FILTER_USD", 14000.0)

# 序列确认 / 共振 / 交易所噪声抑制配置。
INTENT_CONFIRMATION_WINDOW_SEC = _get_int_env("INTENT_CONFIRMATION_WINDOW_SEC", 900)
TOKEN_RESONANCE_WINDOW_SEC = _get_int_env("TOKEN_RESONANCE_WINDOW_SEC", 300)
TOKEN_RESONANCE_MIN_ADDRESSES = _get_int_env("TOKEN_RESONANCE_MIN_ADDRESSES", 2)
EXCHANGE_NOISE_CONFIRMATION_MIN = _get_float_env("EXCHANGE_NOISE_CONFIRMATION_MIN", 0.58)

# Strategy 输出约束配置。
MIN_SIGNAL_USD = _get_float_env("MIN_SIGNAL_USD", 800.0)
MIN_CONFIDENCE = _get_float_env("MIN_CONFIDENCE", 0.71)
MIN_ADDRESS_SCORE = _get_float_env("MIN_ADDRESS_SCORE", 55.0)
MIN_TOKEN_SCORE = _get_float_env("MIN_TOKEN_SCORE", 52.0)
MIN_BEHAVIOR_CONFIDENCE = _get_float_env("MIN_BEHAVIOR_CONFIDENCE", 0.6)
STRATEGY_REQUIRE_NON_NORMAL_BEHAVIOR = _get_bool_env("STRATEGY_REQUIRE_NON_NORMAL_BEHAVIOR", False)

# Signal Interpretation 层配置。
INTERPRETER_CONTINUOUS_WINDOW_SEC = _get_int_env("INTERPRETER_CONTINUOUS_WINDOW_SEC", 300)
INTERPRETER_ABNORMAL_MULTIPLIER = _get_float_env("INTERPRETER_ABNORMAL_MULTIPLIER", 2.0)

# Delivery 路由配置。
ARCHIVE_ENABLE_DELIVERY_AUDIT = _get_bool_env("ARCHIVE_ENABLE_DELIVERY_AUDIT", True)
DELIVERY_ALLOW_EXCHANGE_ANCHOR_PRIMARY = _get_bool_env("DELIVERY_ALLOW_EXCHANGE_ANCHOR_PRIMARY", False)
DELIVERY_ALLOW_LP_OBSERVE = _get_bool_env("DELIVERY_ALLOW_LP_OBSERVE", True)
DELIVERY_ALLOW_EXCHANGE_OBSERVE = _get_bool_env("DELIVERY_ALLOW_EXCHANGE_OBSERVE", False)
EXCHANGE_STRONG_OBSERVE_ENABLE = _get_bool_env("EXCHANGE_STRONG_OBSERVE_ENABLE", True)
EXCHANGE_STRONG_OBSERVE_ALLOWED_REASONS = _get_csv_env(
    "EXCHANGE_STRONG_OBSERVE_ALLOWED_REASONS",
    [
        "exchange_directional_observe",
        "exchange_execution_observe",
    ],
)
EXCHANGE_STRONG_OBSERVE_MIN_USD = _get_float_env("EXCHANGE_STRONG_OBSERVE_MIN_USD", 300000.0)
EXCHANGE_STRONG_OBSERVE_MIN_CONFIRMATION = _get_float_env("EXCHANGE_STRONG_OBSERVE_MIN_CONFIRMATION", 0.68)
EXCHANGE_STRONG_OBSERVE_MIN_QUALITY = _get_float_env("EXCHANGE_STRONG_OBSERVE_MIN_QUALITY", 0.86)
EXCHANGE_STRONG_OBSERVE_MIN_RESONANCE = _get_float_env("EXCHANGE_STRONG_OBSERVE_MIN_RESONANCE", 0.45)
EXCHANGE_STRONG_OBSERVE_MIN_PRICING_CONFIDENCE = _get_float_env(
    "EXCHANGE_STRONG_OBSERVE_MIN_PRICING_CONFIDENCE",
    0.85,
)
EXCHANGE_STRONG_OBSERVE_REQUIRE_CONFIRMED_INTENT = _get_bool_env(
    "EXCHANGE_STRONG_OBSERVE_REQUIRE_CONFIRMED_INTENT",
    False,
)
DELIVERY_ALLOW_DOWNSTREAM_OBSERVE = _get_bool_env("DELIVERY_ALLOW_DOWNSTREAM_OBSERVE", True)
DELIVERY_ALLOW_SMART_MONEY_TRANSFER_OBSERVE = _get_bool_env("DELIVERY_ALLOW_SMART_MONEY_TRANSFER_OBSERVE", False)
DELIVERY_ALLOW_SMART_MONEY_TRANSFER_PRIMARY = _get_bool_env("DELIVERY_ALLOW_SMART_MONEY_TRANSFER_PRIMARY", False)
DELIVERY_SMART_MONEY_EXECUTION_PRIMARY = _get_bool_env("DELIVERY_SMART_MONEY_EXECUTION_PRIMARY", True)
SMART_MONEY_NOTIFY_EXECUTION_ONLY = _get_bool_env("SMART_MONEY_NOTIFY_EXECUTION_ONLY", True)
MARKET_MAKER_NOTIFY_EXECUTION_ONLY = _get_bool_env("MARKET_MAKER_NOTIFY_EXECUTION_ONLY", True)
DELIVERY_LP_WEAK_SIGNAL_ARCHIVE_ONLY = _get_bool_env("DELIVERY_LP_WEAK_SIGNAL_ARCHIVE_ONLY", True)
SMART_MONEY_CASE_WINDOW_SEC = _get_int_env("SMART_MONEY_CASE_WINDOW_SEC", 1800)
ADJACENT_WATCH_ENABLE = _get_bool_env("ADJACENT_WATCH_ENABLE", True)
ADJACENT_WATCH_WINDOW_SEC = _get_int_env("ADJACENT_WATCH_WINDOW_SEC", 1800)
ADJACENT_WATCH_COOLING_SEC = _get_int_env("ADJACENT_WATCH_COOLING_SEC", 3600)
ADJACENT_WATCH_CLOSING_SEC = _get_int_env("ADJACENT_WATCH_CLOSING_SEC", 14400)
ADJACENT_WATCH_MAX_HOPS = _get_int_env("ADJACENT_WATCH_MAX_HOPS", 1)
ADJACENT_WATCH_SUPER_LARGE_USD = _get_float_env("ADJACENT_WATCH_SUPER_LARGE_USD", 1_000_000.0)
ADJACENT_WATCH_FOLLOWUP_MIN_USD = _get_float_env("ADJACENT_WATCH_FOLLOWUP_MIN_USD", 500_000.0)
ADJACENT_WATCH_FOLLOWUP_MIN_RATIO = _get_float_env("ADJACENT_WATCH_FOLLOWUP_MIN_RATIO", 0.40)
ADJACENT_WATCH_STABLE_SUPER_LARGE_USD = _get_float_env("ADJACENT_WATCH_STABLE_SUPER_LARGE_USD", 1_000_000.0)
ADJACENT_WATCH_MAJOR_ASSET_SUPER_LARGE_USD = _get_float_env("ADJACENT_WATCH_MAJOR_ASSET_SUPER_LARGE_USD", 750_000.0)
ADJACENT_WATCH_OTHER_ASSET_SUPER_LARGE_USD = _get_float_env("ADJACENT_WATCH_OTHER_ASSET_SUPER_LARGE_USD", 1_500_000.0)
ADJACENT_WATCH_MAX_NOTIFICATIONS = _get_int_env("ADJACENT_WATCH_MAX_NOTIFICATIONS", 1)
ADJACENT_WATCH_ALLOWED_ROLE_GROUPS = _get_csv_env(
    "ADJACENT_WATCH_ALLOWED_ROLE_GROUPS",
    [
        "market_maker_wallet",
        "smart_money_wallet",
        "alpha_wallet",
        "celebrity_wallet",
    ],
)
ADJACENT_WATCH_EXCLUDE_ROUTER = _get_bool_env("ADJACENT_WATCH_EXCLUDE_ROUTER", True)
ADJACENT_WATCH_EXCLUDE_PROTOCOL = _get_bool_env("ADJACENT_WATCH_EXCLUDE_PROTOCOL", True)
ADJACENT_WATCH_EXCLUDE_EXCHANGE = _get_bool_env("ADJACENT_WATCH_EXCLUDE_EXCHANGE", True)
ADJACENT_WATCH_EXCLUDE_LP_POOL = _get_bool_env("ADJACENT_WATCH_EXCLUDE_LP_POOL", True)
ADJACENT_WATCH_RUNTIME_STRATEGY_ROLE = _get_str_env("ADJACENT_WATCH_RUNTIME_STRATEGY_ROLE", "adjacent_watch")
ADJACENT_WATCH_RUNTIME_PRIORITY = _get_int_env("ADJACENT_WATCH_RUNTIME_PRIORITY", 3)
ADJACENT_WATCH_RUNTIME_MIN_USD = _get_float_env("ADJACENT_WATCH_RUNTIME_MIN_USD", 50_000.0)
ADJACENT_WATCH_NOTIFY_MIN_FOLLOWUP_COUNT = _get_int_env("ADJACENT_WATCH_NOTIFY_MIN_FOLLOWUP_COUNT", 2)
ADJACENT_WATCH_NOTIFY_MIN_CONFIRMATION = _get_float_env("ADJACENT_WATCH_NOTIFY_MIN_CONFIRMATION", 0.62)
ADJACENT_WATCH_NOTIFY_MIN_QUALITY = _get_float_env("ADJACENT_WATCH_NOTIFY_MIN_QUALITY", 0.80)
ADJACENT_WATCH_NOTIFY_MIN_PRICING_CONFIDENCE = _get_float_env("ADJACENT_WATCH_NOTIFY_MIN_PRICING_CONFIDENCE", 0.75)
ADJACENT_WATCH_NOTIFY_MIN_RESONANCE = _get_float_env("ADJACENT_WATCH_NOTIFY_MIN_RESONANCE", 0.40)
ADJACENT_WATCH_NOTIFY_MIN_ABNORMAL_RATIO = _get_float_env("ADJACENT_WATCH_NOTIFY_MIN_ABNORMAL_RATIO", 2.0)
ADJACENT_WATCH_NOTIFY_ALLOWED_STAGES = _get_csv_env(
    "ADJACENT_WATCH_NOTIFY_ALLOWED_STAGES",
    [
        "exchange_arrival_confirmed",
        "swap_execution_confirmed",
        "distribution_confirmed",
    ],
)
DOWNSTREAM_EARLY_WARNING_ENABLE = _get_bool_env("DOWNSTREAM_EARLY_WARNING_ENABLE", True)
DOWNSTREAM_EARLY_WARNING_MIN_ANCHOR_USD = _get_float_env("DOWNSTREAM_EARLY_WARNING_MIN_ANCHOR_USD", 1000000.0)
DOWNSTREAM_EARLY_WARNING_MIN_EVENT_USD = _get_float_env("DOWNSTREAM_EARLY_WARNING_MIN_EVENT_USD", 1000000.0)
DOWNSTREAM_EARLY_WARNING_MIN_CONFIRMATION = _get_float_env("DOWNSTREAM_EARLY_WARNING_MIN_CONFIRMATION", 0.72)
DOWNSTREAM_EARLY_WARNING_MIN_QUALITY = _get_float_env("DOWNSTREAM_EARLY_WARNING_MIN_QUALITY", 0.86)
DOWNSTREAM_EARLY_WARNING_MIN_PRICING_CONFIDENCE = _get_float_env(
    "DOWNSTREAM_EARLY_WARNING_MIN_PRICING_CONFIDENCE",
    0.80,
)
DOWNSTREAM_EARLY_WARNING_MIN_RESONANCE = _get_float_env("DOWNSTREAM_EARLY_WARNING_MIN_RESONANCE", 0.45)
DOWNSTREAM_EARLY_WARNING_MIN_ABNORMAL_RATIO = _get_float_env("DOWNSTREAM_EARLY_WARNING_MIN_ABNORMAL_RATIO", 2.2)
DOWNSTREAM_EARLY_WARNING_MAX_PER_CASE = _get_int_env("DOWNSTREAM_EARLY_WARNING_MAX_PER_CASE", 1)
PERSISTED_EXCHANGE_ADJACENT_EXCHANGE_RELATED_MIN_USD = _get_float_env(
    "PERSISTED_EXCHANGE_ADJACENT_EXCHANGE_RELATED_MIN_USD",
    50000.0,
)
PERSISTED_EXCHANGE_ADJACENT_EXCHANGE_RELATED_MIN_PRICING_CONFIDENCE = _get_float_env(
    "PERSISTED_EXCHANGE_ADJACENT_EXCHANGE_RELATED_MIN_PRICING_CONFIDENCE",
    0.72,
)
LP_VOLUME_SURGE_MIN_RATIO = _get_float_env("LP_VOLUME_SURGE_MIN_RATIO", 1.4)
LP_OBSERVE_MIN_CONFIDENCE = _get_float_env("LP_OBSERVE_MIN_CONFIDENCE", 0.52)
LP_OBSERVE_MIN_USD = _get_float_env("LP_OBSERVE_MIN_USD", 14000.0)
LP_OBSERVE_THRESHOLD_RATIO_FLOOR = _get_float_env("LP_OBSERVE_THRESHOLD_RATIO_FLOOR", 0.55)
LP_OBSERVE_MAX_USD_GAP = _get_float_env("LP_OBSERVE_MAX_USD_GAP", 8000.0)
LP_FAST_EXCEPTION_MIN_SAME_POOL_CONTINUITY = _get_int_env("LP_FAST_EXCEPTION_MIN_SAME_POOL_CONTINUITY", 4)
LP_FAST_EXCEPTION_MIN_VOLUME_SURGE_RATIO = _get_float_env("LP_FAST_EXCEPTION_MIN_VOLUME_SURGE_RATIO", 4.0)
LP_FAST_EXCEPTION_MIN_ACTION_INTENSITY = _get_float_env("LP_FAST_EXCEPTION_MIN_ACTION_INTENSITY", 0.60)
LP_FAST_EXCEPTION_MIN_RESERVE_SKEW = _get_float_env("LP_FAST_EXCEPTION_MIN_RESERVE_SKEW", 0.99)
LP_FAST_EXCEPTION_MIN_PRICING_CONFIDENCE = _get_float_env("LP_FAST_EXCEPTION_MIN_PRICING_CONFIDENCE", 0.85)
LP_PRIMARY_MIN_CONFIDENCE = _get_float_env("LP_PRIMARY_MIN_CONFIDENCE", 0.72)
LP_PRIMARY_MIN_SURGE_RATIO = _get_float_env("LP_PRIMARY_MIN_SURGE_RATIO", 2.2)
LP_FIRST_HIT_PRIMARY_ENABLE = _get_bool_env("LP_FIRST_HIT_PRIMARY_ENABLE", True)
LP_FIRST_HIT_PRIMARY_MIN_USD = _get_float_env("LP_FIRST_HIT_PRIMARY_MIN_USD", 40000.0)
LP_FIRST_HIT_PRIMARY_MIN_CONFIDENCE = _get_float_env("LP_FIRST_HIT_PRIMARY_MIN_CONFIDENCE", 0.66)
LP_FIRST_HIT_PRIMARY_MIN_QUALITY = _get_float_env("LP_FIRST_HIT_PRIMARY_MIN_QUALITY", 0.74)
LP_FIRST_HIT_PRIMARY_MIN_ACTION_INTENSITY = _get_float_env("LP_FIRST_HIT_PRIMARY_MIN_ACTION_INTENSITY", 0.70)
LP_FIRST_HIT_PRIMARY_MIN_RESERVE_SKEW = _get_float_env("LP_FIRST_HIT_PRIMARY_MIN_RESERVE_SKEW", 0.20)
LP_FIRST_HIT_PRIMARY_MIN_PRICING_CONFIDENCE = _get_float_env("LP_FIRST_HIT_PRIMARY_MIN_PRICING_CONFIDENCE", 0.78)
LP_FIRST_HIT_PRIMARY_MIN_SURGE_RATIO = _get_float_env("LP_FIRST_HIT_PRIMARY_MIN_SURGE_RATIO", 1.30)
LP_FIRST_HIT_PRIMARY_MIN_ABNORMAL_RATIO = _get_float_env("LP_FIRST_HIT_PRIMARY_MIN_ABNORMAL_RATIO", 1.80)
LP_FIRST_HIT_PRIMARY_DIRECT_ENABLE = _get_bool_env("LP_FIRST_HIT_PRIMARY_DIRECT_ENABLE", True)
LP_FIRST_HIT_PRIMARY_DIRECT_MIN_USD = _get_float_env("LP_FIRST_HIT_PRIMARY_DIRECT_MIN_USD", 60000.0)
LP_FIRST_HIT_PRIMARY_DIRECT_MIN_CONFIDENCE = _get_float_env("LP_FIRST_HIT_PRIMARY_DIRECT_MIN_CONFIDENCE", 0.70)
LP_FIRST_HIT_PRIMARY_DIRECT_MIN_QUALITY = _get_float_env("LP_FIRST_HIT_PRIMARY_DIRECT_MIN_QUALITY", 0.78)
LP_FIRST_HIT_PRIMARY_DIRECT_MIN_PRICING_CONFIDENCE = _get_float_env("LP_FIRST_HIT_PRIMARY_DIRECT_MIN_PRICING_CONFIDENCE", 0.82)
LP_FIRST_HIT_PRIMARY_DIRECT_MIN_ACTION_INTENSITY = _get_float_env("LP_FIRST_HIT_PRIMARY_DIRECT_MIN_ACTION_INTENSITY", 0.76)
LP_FIRST_HIT_PRIMARY_DIRECT_MIN_RESERVE_SKEW = _get_float_env("LP_FIRST_HIT_PRIMARY_DIRECT_MIN_RESERVE_SKEW", 0.24)
LP_FIRST_HIT_PRIMARY_DIRECT_MIN_SURGE_RATIO = _get_float_env("LP_FIRST_HIT_PRIMARY_DIRECT_MIN_SURGE_RATIO", 1.40)
LP_FIRST_HIT_PRIMARY_DIRECT_MIN_ABNORMAL_RATIO = _get_float_env("LP_FIRST_HIT_PRIMARY_DIRECT_MIN_ABNORMAL_RATIO", 2.00)
LP_BURST_FASTLANE_ENABLE = _get_bool_env("LP_BURST_FASTLANE_ENABLE", True)
LP_BURST_WINDOW_SEC = _get_int_env("LP_BURST_WINDOW_SEC", 60)
LP_BURST_MIN_EVENT_COUNT = _get_int_env("LP_BURST_MIN_EVENT_COUNT", 8)
LP_BURST_MIN_TOTAL_USD = _get_float_env("LP_BURST_MIN_TOTAL_USD", 30000.0)
LP_BURST_MIN_MAX_SINGLE_USD = _get_float_env("LP_BURST_MIN_MAX_SINGLE_USD", 5000.0)
LP_BURST_MIN_VOLUME_SURGE_RATIO = _get_float_env("LP_BURST_MIN_VOLUME_SURGE_RATIO", 6.0)
LP_BURST_MIN_ACTION_INTENSITY = _get_float_env("LP_BURST_MIN_ACTION_INTENSITY", 0.62)
LP_BURST_MIN_RESERVE_SKEW = _get_float_env("LP_BURST_MIN_RESERVE_SKEW", 0.99)
LP_BURST_MIN_PRICING_CONFIDENCE = _get_float_env("LP_BURST_MIN_PRICING_CONFIDENCE", 0.90)
LP_BURST_PRIMARY_MIN_EVENT_COUNT = _get_int_env("LP_BURST_PRIMARY_MIN_EVENT_COUNT", 10)
LP_BURST_PRIMARY_MIN_TOTAL_USD = _get_float_env("LP_BURST_PRIMARY_MIN_TOTAL_USD", 45000.0)
LP_BURST_PRIMARY_MIN_CONFIRMATION = _get_float_env("LP_BURST_PRIMARY_MIN_CONFIRMATION", 0.72)
LP_BURST_PRIMARY_MIN_QUALITY = _get_float_env("LP_BURST_PRIMARY_MIN_QUALITY", 0.78)
LP_BURST_PRIMARY_MIN_VOLUME_SURGE_RATIO = _get_float_env("LP_BURST_PRIMARY_MIN_VOLUME_SURGE_RATIO", 7.5)
LP_BURST_PRIMARY_MIN_ACTION_INTENSITY = _get_float_env("LP_BURST_PRIMARY_MIN_ACTION_INTENSITY", 0.70)
LP_DIRECTIONAL_COOLDOWN_SEC = _get_int_env("LP_DIRECTIONAL_COOLDOWN_SEC", 60)
SMART_MONEY_VALUE_BONUS_MAX = _get_float_env("SMART_MONEY_VALUE_BONUS_MAX", 0.08)
SMART_MONEY_VALUE_THRESHOLD_RATIO = _get_float_env("SMART_MONEY_VALUE_THRESHOLD_RATIO", 2.10)
SMART_MONEY_NON_EXEC_GATE_FLOOR = _get_float_env("SMART_MONEY_NON_EXEC_GATE_FLOOR", 0.61)
MARKET_MAKER_OBSERVE_GATE_FLOOR = _get_float_env("MARKET_MAKER_OBSERVE_GATE_FLOOR", 0.59)
MARKET_MAKER_OBSERVE_MIN_CONFIRMATION = _get_float_env("MARKET_MAKER_OBSERVE_MIN_CONFIRMATION", 0.46)
MARKET_MAKER_OBSERVE_MIN_RESONANCE = _get_float_env("MARKET_MAKER_OBSERVE_MIN_RESONANCE", 0.32)
MARKET_MAKER_OBSERVE_VALUE_BONUS_MAX = _get_float_env("MARKET_MAKER_OBSERVE_VALUE_BONUS_MAX", 0.05)
MARKET_MAKER_PRIMARY_STRICT = _get_bool_env("MARKET_MAKER_PRIMARY_STRICT", True)
LP_VALUE_BONUS_MAX = _get_float_env("LP_VALUE_BONUS_MAX", 0.03)
EXCHANGE_DIRECTIONAL_VALUE_BONUS_MAX = _get_float_env("EXCHANGE_DIRECTIONAL_VALUE_BONUS_MAX", 0.05)
EXCHANGE_DIRECTIONAL_VALUE_THRESHOLD_RATIO = _get_float_env("EXCHANGE_DIRECTIONAL_VALUE_THRESHOLD_RATIO", 1.85)
LIQUIDATION_RISK_MIN_SCORE = _get_float_env("LIQUIDATION_RISK_MIN_SCORE", 0.66)
LIQUIDATION_EXECUTION_MIN_SCORE = _get_float_env("LIQUIDATION_EXECUTION_MIN_SCORE", 0.86)
LIQUIDATION_PROTOCOL_HIT_BONUS = _get_float_env("LIQUIDATION_PROTOCOL_HIT_BONUS", 0.18)
LIQUIDATION_CONTINUITY_BONUS = _get_float_env("LIQUIDATION_CONTINUITY_BONUS", 0.10)
LIQUIDATION_RESONANCE_BONUS = _get_float_env("LIQUIDATION_RESONANCE_BONUS", 0.10)
LIQUIDATION_SURGE_BONUS = _get_float_env("LIQUIDATION_SURGE_BONUS", 0.08)
LIQUIDATION_MIN_USD = _get_float_env("LIQUIDATION_MIN_USD", 35000.0)
LIQUIDATION_PRIMARY_MIN_USD = _get_float_env("LIQUIDATION_PRIMARY_MIN_USD", 125000.0)
DELIVERY_ALLOW_LIQUIDATION_RISK_OBSERVE = _get_bool_env("DELIVERY_ALLOW_LIQUIDATION_RISK_OBSERVE", True)
DELIVERY_ALLOW_LIQUIDATION_EXECUTION_PRIMARY = _get_bool_env("DELIVERY_ALLOW_LIQUIDATION_EXECUTION_PRIMARY", True)
SPILL_REPLAY_INTERVAL_SEC = _get_int_env("SPILL_REPLAY_INTERVAL_SEC", 3)
SPILL_REPLAY_MAX_BATCH = _get_int_env("SPILL_REPLAY_MAX_BATCH", 150)
SPILL_REPLAY_QUEUE_WATERMARK = _get_int_env("SPILL_REPLAY_QUEUE_WATERMARK", 1200)

# 低 CU / RPC 监听优化配置。
LOW_CU_MODE = _get_bool_env("LOW_CU_MODE", True)
LISTENER_INCLUDE_ACTIVE_LP_POOLS_IN_MAIN_LOG_SCAN = _get_bool_env(
    "LISTENER_INCLUDE_ACTIVE_LP_POOLS_IN_MAIN_LOG_SCAN",
    False,
)
LP_SECONDARY_SCAN_ENABLE = _get_bool_env("LP_SECONDARY_SCAN_ENABLE", True)
LP_SECONDARY_SCAN_INTERVAL_SEC = _get_float_env(
    "LP_SECONDARY_SCAN_INTERVAL_SEC",
    18.0 if LOW_CU_MODE else 12.0,
)
PRODUCER_POLL_INTERVAL_SEC = _get_float_env("PRODUCER_POLL_INTERVAL_SEC", 1.0)
LISTENER_TOPIC_CHUNK_SIZE = _get_int_env("LISTENER_TOPIC_CHUNK_SIZE", 50)
LISTENER_SELECTIVE_TX_FETCH_MAX_COUNT = _get_int_env("LISTENER_SELECTIVE_TX_FETCH_MAX_COUNT", 20)

# Token metadata 本地持久缓存配置。
TOKEN_METADATA_CACHE_ENABLE = _get_bool_env("TOKEN_METADATA_CACHE_ENABLE", True)
TOKEN_METADATA_CACHE_PATH = _get_str_env("TOKEN_METADATA_CACHE_PATH", "data/token_metadata_cache.json")

# RPC 重试 / 退避 / 熔断配置。
RPC_BACKOFF_BASE_SEC = _get_float_env("RPC_BACKOFF_BASE_SEC", 1.0)
RPC_BACKOFF_MAX_SEC = _get_float_env("RPC_BACKOFF_MAX_SEC", 20.0)
RPC_RETRY_MAX_ATTEMPTS = _get_int_env("RPC_RETRY_MAX_ATTEMPTS", 5)
RPC_CIRCUIT_BREAKER_SEC = _get_int_env("RPC_CIRCUIT_BREAKER_SEC", 30)

# 本地归档开关配置。
ARCHIVE_ENABLE_RAW_EVENTS = _get_bool_env("ARCHIVE_ENABLE_RAW_EVENTS", False)
ARCHIVE_ENABLE_PARSED_EVENTS = _get_bool_env("ARCHIVE_ENABLE_PARSED_EVENTS", False)
ARCHIVE_ENABLE_SIGNALS = _get_bool_env("ARCHIVE_ENABLE_SIGNALS", True)
ARCHIVE_ENABLE_CASES = _get_bool_env("ARCHIVE_ENABLE_CASES", False)
ARCHIVE_ENABLE_CASE_FOLLOWUPS = _get_bool_env("ARCHIVE_ENABLE_CASE_FOLLOWUPS", True)
